FROM centos:7

RUN yum -y update && yum -y install wget nano && yum -y groupinstall "Development Tools"

WORKDIR /usr/share/

#instalacion Redis
RUN wget http://download.redis.io/redis-stable.tar.gz  && \
	tar xvzf redis-stable.tar.gz && \
	cd redis-stable && make && make install
	
RUN mkdir /etc/redis && mkdir /var/redis && \
	cp redis-stable/utils/redis_init_script /etc/init.d/redis_6379 && \
	cp redis-stable/redis.conf /etc/redis/6379.conf 

#config Redis
RUN sed -i 's/daemonize no/daemonize yes/g' /etc/redis/6379.conf  && \
	sed -i 's/protected-mode yes/protected-mode no/g' /etc/redis/6379.conf  && \
	/etc/init.d/redis_6379 start

EXPOSE 6379

CMD ["/bin/bash"]
